### ISSUE TITLE
DynaDungeons 0.1 release

### ISSUE THREAD

**Issue by akien-mga** [akien-mga/dynadungeons#26]
_Release early, release often._

DynaDungeons needs a first release so that we can start talking about the project in the Godot and libre games communities.

Some time ago I've set up some first milestones for DynaDungeons, and we're not far way from reaching the 0.1 "Move Zig" milestone: https://github.com/akien-mga/dynadungeons/milestones

Here are links to the main changes that relate to this milestone:

**Gameplay**
- [x] Implement basic gameplay, characters move on a tile-based 2D level and drop bombs to destroy blocks and kill one another.
- [x] Players can have multiples live (#3)
- [ ] Add first set of powerups (partly done, #5, #11)
- [x] Bomb explosions destroy powerups in range (#4)

**User Interface**
- [ ] In-game UI overlay (#15)
- [ ] Gameover screen (#16)

**Music and SFX**
- [x] Initial level music
- [x] Initial sound effects (#12)

**Comment by akien-mga** [comment]
BTW the actual issues that should compose the milestone are open to discussion, if there are things that you absolutely want to see in a first release, say so :)

**Comment by ObaniGemini** [comment]
I can make others musics. For sound effects, I think we should search on opengameart.org . Do we need an official logo ?

**Comment by akien-mga** [comment]
Another music could be cool. I'd like something that takes inspiration from typical fantasy dungeons and at the same time something arcade-like à la Bomberman... I leave it up to you to be creative, the main object right now is to have fun doing stuff :P

For the sound effects, @deliciousfudge made some proposals from soundbible, which should already allow us to be done with the first set of sound effects (of course most of them are placeholders and will have to be improved as the game becomes more interesting).

For the logo, it's not a priority for me, for the time being I'm using a bomb sprite and it's fine IMO. But if you want to work on something, feel free to do it :)

**Comment by akien-mga** [comment]
I've added a couple sound effects from soundbible. What's left for this milestone is the UI overlay (showing player lives mostly) and the gameover screen, plus maybe a couple powerups.

**Comment by ghost** [comment]
Looking good! 

The gameover screen is about halfway done. It just needs an action to dismiss the prompt (I think I saw left-click mentioned somewhere) and re-direct to the main menu, plus some sort of logic to determine a draw.

I'm a bit busy at the moment but happy to have a look at gameover and UI on Sunday.

**Comment by akien-mga** [comment]
@deliciousfudge Could you make some progress on the gameover screen?

I think I'll get started on the in-game UI overlay, unless you also have a WIP for it already.

**Comment by ghost** [comment]
@akien-mga Sorry about the big delay. Have been quite busy lately and unfortunately that meant side-projects had to be put aside :P 

I'm just making some changes to the gameover screen now, but don't have any WIP for the UI overlay.

**Comment by akien-mga** [comment]
No problem, I've been mostly busy working on Godot upstream with bug triage, PR review, etc., so I haven't touched dyna much lately. I've just pushed a quite invasive change though to move to the new tscn/tres human-readable format that was just added in Godot upstream, so you'll need to build the latest Godot and likely resave your changes in the new format.

So before pulling, make sure to keep a copy of your modified .xscn files, then you'll be able to reopen them and them save as .tscn (and then once you've put them on top of the current HEAD .tscn files, check the diff as some resource references might need to be fixed manually).

**Comment by ghost** [comment]
No problem. Will look into it.

**Comment by JuanDidNothingWrong5** [comment]
Not a high priority at all akien, voting to close.
